# Generated by Django 3.2.20 on 2023-07-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_topic', to='examquiz.quizsection'),
        ),
    ]
